### ISSUE TITLE
thanks for your work and i wanna know how to use your release.

### ISSUE THREAD

**Issue by CelestialEclipse** [easly1989/ffxiv_act_dfassist#1]
Hello and thanks a lot.I downloaded your project and i got the base in https://github.com/devunt/DFAssist.But i dont know how to update the base version to the 4.2,i hope maybe you can teach me about how to use your release?Please forgive me if there is any offense.Thank you very much!

**Comment by easly1989** [comment]
ok so, 
the link you provided is for the **standalone** version developed by **devunt**.
And I don't know if he is still developing the sources, you should check on his github (which is the one you linked btw)

My version of the program works using the [ACT ](http://advancedcombattracker.com/download.php)

It is a plugin, and like any other plugin for ACT you just need to enable it in the plugin tab. (Also you will need to have the FFXIV  plugin installed!) [here is a guide](https://www.reddit.com/r/ACTOverlayPlugin/comments/3b7ogz/instructionslatest_download/) if you are not familiar with ACT installation

Also, i made a simple program to install ACT with some of the most used plugins (but it has been a while since last time i checked .. so it may not work ^^'... in that case you should do it manually following the link above!) [you can try it here](https://github.com/easly1989/ffxiv_actor/releases/download/1.9.7/ActorConsole_1.9.7.zip)

If you have any other question feel free to ask :)

have a nice day

**Comment by CelestialEclipse** [comment]
really thx for your help!

**Comment by junyahuang** [comment]
hello, I also try to install ur plugin, but I couldnt find the .dll that I need, and cant enable it.
