### ISSUE TITLE
A: Error while analyzing Message: Method not found: 'Void Advanced_Combat_Tracker.TraySlider.ShowTraySlider(System.String)'.

### ISSUE THREAD

**Issue by RequestForCommit** [easly1989/ffxiv_act_dfassist#20]
Got this error today before and after the update.

![dfassist](https://user-images.githubusercontent.com/55059496/64491677-4d198e00-d239-11e9-8b79-db570ba1620c.PNG)

**Comment by RequestForCommit** [comment]
Also, it seems queueing into Mentor Roulette (or any) registers as a "Duty" whereas queueing into a singular dungeon registers as a "Roulette". "Could not find Roulette with 0, report to the dev!" when queueing into Sastasha.

**Comment by easly1989** [comment]
Your first problem should be fixed in version 2.0.4.
ACT was updated and this caused the problem.

The other problem is something I cannot check right now (as I have finished my subscription to FF and I don't think I'll renew it in the near future ^^').
So, you may want to debug it on your own, or wait for a kind soul to do that ...
I've checked the other forks of this plugin to see if there were major changes about the roulette and instance coding, but found nothing unfortunately :(

**Comment by RequestForCommit** [comment]
No worries, thanks for the work you’ve done on it so far.

**Comment by EQAditu** [comment]
Sorry for the issue I caused with the TraySlider.  Technically the method signature changed from a strict standpoint, but in a way it didn't functionally change so I didn't catch it.  I imagine recompiling with no code changes fixed it because the compiler is smarter than the runtime.

**Comment by easly1989** [comment]
No need to say sorry @EQAditu,
I didn't check the updates, and so didn't notice the change in the method.

You are doing a great work with ACT, and also added the needed modifications I requested for the slider, so Thank you! Really, Thank you! :)
