### ISSUE TITLE
Toasts not working

### ISSUE THREAD

**Issue by CloysterOyster** [easly1989/ffxiv_act_dfassist#29]
So when my queue pops I actually get nothing (no chat message nor ACT Toast). Tried uninstalling and reinstalling, problem persists. When I press Test Configuration the ACT Toast pops up, but no chat message.
![Advanced_Combat_Tracker_e8fgpCmFmK](https://user-images.githubusercontent.com/32553856/65646896-7cf2c080-dfb1-11e9-8d55-c2cdd64abd21.png)
![Advanced_Combat_Tracker_lbqrTFeZwt](https://user-images.githubusercontent.com/32553856/65647241-ed4e1180-dfb2-11e9-8257-7ce353b7eb2f.png)

**Comment by Rarisu** [comment]
Can confirm this bug.
This used to work on a previous version of Windows.
However ever since I updated to Windows 10 Build 1903, Toasts has stopped giving notifications.

**Comment by easly1989** [comment]
Sorry for the late answer.
Honestly as I can read from the image/logs it should all work correctly.
Ensure to have disable the "Do Not Disturb" function of Widows 10, that automatically hides all toasts when playing a game, and to use your game in Borderless Windowed (or Windowed) mode (otherwise the toast will not show over the fullscreen game).

Give the [2.0.9](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.0.9) a try, and report back when you can :)

**Comment by Aiakio** [comment]
Hi @easly1989,

Exactly the same issue here. Plugin itself is working like in the screenshots from OP. It just refuses to show any notifications outside of ACT. No Windows Toasts, no ACT Toasts. The only things working are voice output and Notifications inside ACT (Notifications-Tab).

I did not test: Discord, Telegram, Pushbullet. Im on v2.2.13.0.

DND ist always off for me. I dont like that feature.
