### ISSUE TITLE
Flashing Taskbar regardless of the checkbox.

### ISSUE THREAD

**Issue by fchud** [easly1989/ffxiv_act_dfassist#30]
DFAssist 2.0.8, latest ACT, win 10

the ffxiv taskbar is flashing upon notification received regardless of the checkbox status.

i guess,
**OnSendNotification** in _TaskbarFlashHelper.cs_ is lacking the actual check of the checkbox state, like in TTS, for example:
```
            if(!MainControl.FlashTaskbar.Checked)
                return;
```

**Comment by easly1989** [comment]
Sorry for the late answer, I've been really busy IRL..
Anyway I just implemented the fix you just proposed and fixed the relative issue!

next time you can also do a pull request, so that you can take credit for the fix itself ;)
Anyway, version [2.0.9](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.0.9) should work as expected

**Comment by fchud** [comment]
> next time you can also do a pull request, so that you can take credit for the fix itself ;)

i couldn't _definitively_ confirm the fix, because i was not able to successfully compile the project.
so i just left it as a guess.

anyway, thanx for the fix.
