### ISSUE TITLE
Update via ACT not  working correctly

### ISSUE THREAD

**Issue by FlorianOsewald** [easly1989/ffxiv_act_dfassist#36]
Hi there, 

for a while now i've noticed that the update via ACT is not working correctly. 
If an update is available on the repo the entry in the plugin-listing is updated and shows the correct version, while the Plugin-Detail Tab does not.
This is usually fixed by removing the plugin from ACT and fresh-installing the plugin from the repo.
To confirm if this wasnt something like a cached gui, i set the system up on two PCs with similar hardware. One of them updated the plugin via ACT, the other by removing it from ACT and re-installing via repo. 
Both ACT showed Version 2.1.3.0 in the plugin listing. The one who updated via repo had the above mentioned outdated version in the detail view, the clean install ACT showed the correct version in both the detail view as well as the plugin listing. 
As suspected only the ACT with the clean installed plugin worked correctly when doing test-queues. 

If any more information is needed to troubleshoot this, i'd be glad to help out how i can.

Best regards

**Comment by easly1989** [comment]
Thank you for the detailed explanation and testing.
Tomorrow I'll look into my code to ensure that it is not a problem on my side (as I strictly followed the guidelines made from the ACT dev), and report on the ACT forum if needed.

I"ll keep you updated here :)

**Comment by EQAditu** [comment]
So, more or less it was always an issue but not one that was obvious until certain parts were split out into the `libs` folder like `DFAssist.Contracts.dll` and `DFAssist.Core.dll`.

The main ACT application when loading plugin assemblies does not do so directly from disk.  This is because the CLR will lock the file and not release the handle until the application has closed.  So when DFAssist updates, the main plugin file can get replaced because it is not locked, but anything loaded through the assembly resolver gets locked and cannot be updated.  When it was unchanging assemblies like Newtonsoft.Json, it was unnoticed because the replacement file was likely the same version as the one that was locked.

It looks like you use `Assembly.LoadFrom(string)` that accepts a file path.  ACT's plugin system uses the following method to load plugins to avoid file locks: [`Assembly.Load`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=netframework-4.8#System_Reflection_Assembly_Load_System_Byte___System_Byte___)`(byte[], byte[])`.

It might not be a drop-in replacement for you, however.  These two methods will create different assembly load contexts.  It might work perfectly, or it might throw a weird error saying it can't cast A to B, even though they look the same.

**Comment by easly1989** [comment]
I'll try loading assemblies that way, hopefully this will be the last time i take care of that resolver!

Thank you for the detailed explanation, really appreciated :)

**Comment by easly1989** [comment]
[2.1.4](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.4) should address this issue.
Let me know if it works

**Comment by EQAditu** [comment]
I feel like you won't have positive verification until people update from 2.1.4 to a newer one... but as long as the resolver worked okay for loading things, I bet it will work better.

**Comment by FlorianOsewald** [comment]
Hi there, thanks so much for the quick update.
I'll clean install the new version from the repo once i'm home. 
As for what @EQAditu  said, they're correct, however, I'll do a small test by installing the Plugin, using it for a couple minutes and then try and delete the plugin without closing ACT. 
So far, I was never able to do that because of the locked file, so if the file isn't locked anymore, my general assumption would be that i can just remove the plugin without an error. 
Will report back in a couple hours when i'm home and again thanks so much for the quick help!

**Comment by easly1989** [comment]
Ehehe thats true 😂
We'll see with next release, I'll keep this issue open until then (I don't think it will take too much anyway!)

@FlorianOsewald ok, I'll wait for your report too (and I'll give it a try myself xD); *fingers crossed*

**Comment by EQAditu** [comment]
I believe having the sub-DLLs will have one last side-effect you'll need to consider for the next version.

The FFXIV plugin also has multiple assemblies, even though they are embedded into one file.  This has the effect of keeping the child assemblies in memory when the main plugin assembly deinits and inits the new version.  The new plugin looks for the child assemblies and the CLR says they're already loaded... but they're the old versions.  Ravahn does detection on the child assemblies' versions and tells the user to restart ACT to finish the update.

I believe you'll have to do something similar if you update your child assemblies at the same time as the main plugin.  Just consider a friendly and straightforward message to provide and hope that people understand what to do.

**Comment by easly1989** [comment]
It is for sure a possible solution, I'll add this quick fix asap.

Honestly i would like to find a gracefull way to just unload those libraries.. But idk if there is actually a way.. I'll investigate!

**Comment by EQAditu** [comment]
The only real way to unload libraries is to destroy the AppDomain that they exist in.  ACT currently uses only one AppDomain because marshalling data across boundaries is expensive(slow).  .NET 4.8 is the last .NET version that will have the concept of multiple possible AppDomains.  .NET 5(aka the next .NET Core) will have only one AppDomain and still no way to unload assemblies.  Maybe there will be a way to require a certain version and not accept the CLR's shortcut that the assembly name is already loaded.

ACT only pretends to unload old plugins when it updates them.  That's why it's important that old versions clean up as much as possible when deinit is called.  They have to play dead, because it cannot be forced upon them.

**Comment by easly1989** [comment]
Got it, so a messagebox will be! :)

**Comment by FlorianOsewald** [comment]
@easly1989 just returned home and so far it seems to work. I'm able to remove the plugin without the usual file-locked exception popping up, so here's hoping that the issue is fixed :)  The Version-string in the detail-view doesn't seem to be updated tho, but i would hardly consider this an issue ;)

**Comment by easly1989** [comment]
Most probably as @EQAditu said, after the automatic update you will need to restart ACT to make it work properly (and maybe that covers up also that version string).

Anyway i think this can be closed,
have a nice game/day/journey everyone! :)
