### ISSUE TITLE
When I back to character selector.

### ISSUE THREAD

**Issue by ffxivvillein** [easly1989/ffxiv_act_dfassist#4]
dfassist is not working. I need restart ACT for rework.

**Comment by easly1989** [comment]
It may be related to the new patch.
if you have a more detailed error please send it here and I'll will try to fix it asap! 

Have a safe journey 😀

**Comment by ffxivvillein** [comment]
After I log out and log in any character, ACT don't catch Match and haven't log message too.

**Comment by easly1989** [comment]
I did not have the time to test it,
This weekend i'll try to reproduce your problem and find a possible fix!
I'm sorry for the inconvenience.

If you (or anybody else) happens to find a possible solution, 
feel free to suggest me it with a pull request ;)
(as I really don't have a lot of spare time, and i also would like to play every now and then XD)

**Comment by easly1989** [comment]
@ffxivvillein should be fixed in version 1.5.1
[https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/1.5.1](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/1.5.1)

Delete the old plugin folder and all of its content before extracting this new version! (To avoid conflicts!)

Reopen the issue if you still have the problem.
