### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by comwares** [easly1989/ffxiv_act_dfassist#45]
I wanted to report what appears to be a memory leak with the DF Assist ACT plugin.  I noticed when streaming the last couple nights that my Discord and Google Chrome were crashing while ACT was up.  When I checked Task Manager ACT was using 57 GB of RAM and was at 99% utilization.  Disabling the DFAssist.dll plugin caused the RAM usage to drop back down to about 200 MB again which is more typical.  I'm not sure what's causing it but I have temporarily disabled the plugin for now.  The RAM usage only creeps up slowly so, for me with 64 GB of RAM, it takes about 45min before I run out of memory and other applications begin crashing.

**Comment by easly1989** [comment]
I have never experienced such a degradato of memory usage, and I have kept it up for hours (and I only have 16gb ram).

I will do some profiling, and try to catch any possibile memory leak..

You could trying using only ffxiv plugin and DFAssist and see if anything changes.. (maybe there is another plugin that is conflicting and causing the leak?)

Let me know if you do other tests

**Comment by comwares** [comment]
Thanks, I'll try that out during raid tomorrow night.  It wasn't occuring until the 5.11 patch when they added The Epic of Alexander (Ultimate).  I'm not sure if there was a version update to the DF Assist plugin around the same time but I'll play around with it a bit more.  For now I've just opted to disable DF Assist when I'm raiding.  I probably won't have time to troubleshoot further until Thursday.

**Comment by easly1989** [comment]
As far as I can tell this is the first time someone has a problem related to memory while using this plugin. So it may be something related to a latest update (I'm using ravahn Machina instead of my homemade packet handler for example in latest releases) or some conflict with another plugins DLL (?)

I'm doing a stress test, keeping ACT and the plugin UP while receiving packets (and showing toast/tts notifications every 5 minutes), but for now memory has never spiked up more than 60MB, i'll keep you updated.

For your testing, take your time, be sure that we'll solve this issue in a way or another ;)
Thank you for your report and your availability

**Comment by xeropresence** [comment]
I've been looking into this as well. 

I think something is broken inside FFXIVNetworkProcessHelper as ActiveProcess is always default
_ffxivNetworkMonitor.ProcessID is always 0


I attached ant and got this

https://i.imgur.com/T4Ob1No.png

All of that was in the gen2 heap.

**Comment by xeropresence** [comment]
Yea, what exactly is this class supposed to be doing? The OnMessageReceived event never seems to get called yet im still getting notifications.

**Comment by easly1989** [comment]
That is something we should point out to @ravahn at this point.
Maybe I've implemented the packet handler the wrong way, or maybe he has to work on some memory tweaks on his side.

Also, your commit on the ActiveProcess selection should push memory down a little bit as it will not create a new process until the old one has exited.

i'm going to make a new release and push it, so that you guys can test it and report if there is any upgrade in performance

**Comment by ravahn** [comment]
Havent debugged this recently,  but here is the first thing I would check. The code which releases the buffers allocated by NetworkBufferFactory will not get invoked if an exception happens somewhere in the public events.  This would explain why many gigabytes of buffers get allocated, since they never get freed.

Are any unhandled exceptions being raised in the OnMessageSent/OnMessageReceived delegates?

**Comment by xeropresence** [comment]
Just encountered it again, this time i had visual studio attached. No exceptions were being thrown when it occurred. My system had become unstable before I was able to set a breakpoint in the OnMessageReceived event but I don't think it was being called.

**Comment by ravahn** [comment]
I'm trying to reproduce a memory leak locally but haven't been able to yet.  Can anyone provide more details of when the problem happens - are there other plugins enabled? does it always happen or only sometimes?  Does it only happen in certain zones?

I do see that DFAssist is loading its own instance of Machina classes, rather than using the methods exposed by FFXIV_ACT_Plugin.  You could improve performance significantly by not creating another Machina instance, which has to decode and reassemble TCP and IP packets, and instead use the FFXIV_ACT_Plugin IDataSubscription.NetworkReceived event.

If there's a reason not to do this, I recommend setting the UseSocketFilter property to true.  this will do port-level filtering on the socket / winpcap device, which significantly reduces the memory and cpu footprint when streaming or downloading large files.  I added this feature because people reported packet loss from Machina while performing these activities, which I traced down to very small (64kb) buffers in windows networking that I just couldnt work around / increase.

**Comment by xeropresence** [comment]
I've had it happen in normal raids, alliance raids, trials, hitting a training dummy, and even just idling infront of my house.  When it happens it seems to happen very quickly going from average memory usage to hitting the physical memory limits and pushing stuff into the page file

**Comment by comwares** [comment]
My technical background is not strong enough to keep up with some of the troubleshooting others have been up to above.  I came to report that I updated to v2.2.6 today and the issue was still present.

**Comment by Garash2k** [comment]
Here's more information of a leak that happened using 2.2.6
I have no other plugins but FFXIV_ACT_Plugin (2.0.4.4) and DFAssist installed
I did a memory dump of ACT taking literally all of my computer's ram. (Task Manager. right click process, Create dump file)
I'd attach it, but it's 13GB
Debugging it using a visual studio enterprise trial I just installed at home, I see that...
There's probably something wrong with Machina.NetworkBufferFactory+Buffer
https://i.imgur.com/rZhcLK5.png
https://i.imgur.com/Blqemoy.png
https://i.imgur.com/kYh2ypr.png

Advanced_Combat_Tracker.LogLineEntry is sizable, but that might be due to 4 hours of raiding
https://i.imgur.com/jkD1VvT.png
https://i.imgur.com/OcStss1.png

And here's the 3rd biggest, Dictionary<String, Object>
https://i.imgur.com/bjW8QIq.png
https://i.imgur.com/CemRKcB.png

@ravahn 's advice of not using a new Machina instance seems like it could be a good solution.

**Comment by xeropresence** [comment]
Can you check the size of the dump compressed, and see if its too large to upload somewhere? I've had memdumps go from 24gb to 2gb in a rar.

**Comment by Garash2k** [comment]
Wow you're right, it went down to ~300M 7-zipping it.
Uploaded: https://drive.google.com/file/d/1YYag_yIUdVs4wRjOHgzIy8psz7ILkoOz/view?usp=sharing

**Comment by Garash2k** [comment]
At first I was using a different program to analyse the dump, DebugDiag 2 Analysis.

the 14GB dump is un analyzable with it, it'd probably take half a day if it didn't timeout, but I had another smaller (3GB) memory dump with the previous version of dfassist, and I see this chain taking up 1GB in the weird reports files it makes that I've attached. Looking at it the 3GB dump might not be the problematic leak, but I'll attach the reports just in case.

https://i.imgur.com/v4p89dE.png

[Reports.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3883363/Reports.zip)

**Comment by easly1989** [comment]
> I'm trying to reproduce a memory leak locally but haven't been able to yet. Can anyone provide more details of when the problem happens - are there other plugins enabled? does it always happen or only sometimes? Does it only happen in certain zones?
> 
> I do see that DFAssist is loading its own instance of Machina classes, rather than using the methods exposed by FFXIV_ACT_Plugin. You could improve performance significantly by not creating another Machina instance, which has to decode and reassemble TCP and IP packets, and instead use the FFXIV_ACT_Plugin IDataSubscription.NetworkReceived event.
> 
> If there's a reason not to do this, I recommend setting the UseSocketFilter property to true. this will do port-level filtering on the socket / winpcap device, which significantly reduces the memory and cpu footprint when streaming or downloading large files. I added this feature because people reported packet loss from Machina while performing these activities, which I traced down to very small (64kb) buffers in windows networking that I just couldnt work around / increase.

Sorry for the late answer.
Anyway, no there is no reason to use my own instance of Machina, but didn't find any documentation about the FFXIV_ACT_Plugin IDataSubscription.NetworkReceived or anthing.

Tomorrow I'll switch to this event and remove the reference to Machina, we'll see if this improves the overall performance.

**Comment by easly1989** [comment]
@ravahn I was trying to use the event you suggested but I'm finding some problems as I'm missing some references (and I don't know where to find them)

I should use, specifically, the reference to FFXIV_ACT_Plugin.Common to subscrive to DataSubscription events. Where do I find it?

And just to be 100% clear, using the NetworkReceived event is like using the FFXIVNetworkMonitor.MessageReceived event, right?

Does your plugin also exposes the FFXIV Process?  (so that i could avoid finding it by name)

----

So, I've found the SDK, hope that version 2.0.4.4 is the right now, gonna test it and report back as soon as I'm done

**Comment by easly1989** [comment]
[DFAssist_2.2.7_no_machina.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3887147/DFAssist_2.2.7_no_machina.zip)

Just used the FFXIV_ACT_Plugin NetworkReceived event, and removed Machina and Machina.FFXIV references.

Please let me know if you have better luck with this version

**Comment by Garash2k** [comment]
I used 2.2.7 and saw no leak, I'll report again tomorrow.

**Comment by comwares** [comment]
I've been using v2.2.10 today and have not experienced a leak thus far either.
