### ISSUE TITLE
Unknown duty 195

### ISSUE THREAD

**Issue by ruminyan** [easly1989/ffxiv_act_dfassist#55]
[20:39:41] Could not find Duty with 195, report to the dev!
[20:39:41] Q: Matched [195 - Unknown Duty (195)]

195 is The Triple Triad Battlehall

**Comment by easly1989** [comment]
Unfotunately, it seems like squarenix is changing the opcodes on every hotfix.
So I'm waiting for someone that helps me put on a sustainable way to update this code, you can check the "eventual" progress here #52 

Until then, there is nothing i can do to make the plugin work.
(And if you go check the other DFassist around github, are all stopping the development because of this...)
